name: Test with pytest

on:
  push:
  pull_request:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *' # Run every day at midnight

env:
  DJANGO_SECRET_KEY: "abc123"
  DEBUG: "True"

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
      - run: uv sync --all-extras --dev
      - run: uv run pytest -v